### PR TITLE
`Feature` and `isfeaturecollection`

### PR DESCRIPTION
**Pull request by rafaqz**
This PR rounds out features a little more, adding `isfeaturecollection` and a wrapper object `Feature`.

An `AbstractVector{Feature}` is then defined as the basic default feature collection.

Also updates the tests to better use the new defaults and `testfeature` and `testfeaturecollection`.

### CODE REVIEW

**Comment by rafaqz** [comment]
Ok yes it is a little confusing using `geomtrait`. It's wont' make any difference for performance, it just lets us standardise method dispatch instead of always needing a block like this everywhere: 

```julia
if GeoInterface.isfeature(x) 
    ... 
elseif GeoInterface.isfeaturecollection(x) 
    ...
elseif GeoInterface.isgeometry(x) 
    ... 
end
```

**Comment by evetion** [comment]
GeomTrait and FeatureTrait and FeatureCollectionTrait as options for a trait method?

**Comment by rafaqz** [comment]
Yep. I added the `trait` method here to demonstrate as it's only a few lines. Works well to apply the same methods on both features and geometries.

**Comment by evetion** [comment]
Looks good! Is the `NamedTupleFeature` something you use yourself?

**Comment by rafaqz** [comment]
Yeah Im experimenting with what to return from `extract` in Rasters.jl. It should be some kind of feature.

Also we need something to run the tests on here, the reason its in this PR and not separate.

**Comment by rafaqz** [comment]
Lets not register this yet Im not 100% sure about it

**Pull request merged**
